### ISSUE TITLE
Assignment 4-3 - Space Invaders

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#15]
# Space Invaders (Code Along)

Watch and code along with this talk, [Mary live-codes a JavaScript game from scratch](https://vimeo.com/105955605).

I could not find (or think of) an ES6 assignment that would have been appropriate to drop on you guys tonight. But I did find some other instructors gave this video to code along with. There's some great review and new ideas here, and it's fun. I think you will enjoy it!

**Comment by nickpizzo** [comment]
http://pizzounit.github.io/SpaceInvadersCodeAlong/

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/dLRQd4XuMRjP2/200w_d.gif)
