### ISSUE TITLE
Assignment 5-3 - Github Profile II

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#19]
# Github Profile II
## Description

We are going to continue to create an AJAX powered Github profile viewer.
### Deliverables
- [ ] A publicly visible website on `gh-pages`
### Explorer Mode.

Use the classwork from today as a jumping off point.
Make it look better, I did no design to it. You can merge this into your project from yesterday, or you can pull in parts of your project from yesterday into today's example. Do what you deem to be best.
Add a text field that takes you to the github user's profile who's name you type in. The navigation between Profile and Repos should be updated to work.
### Adventure Mode

Use `Backbone.Model` and `Backbone.View` to render the pages.
### Epic Mode

Your textfield does auto completion of github user names as you type.

**Comment by nickpizzo** [comment]
http://pizzounit.github.io/GHProfile/#pizzounit
