### ISSUE TITLE
Assignment 6-1 - Refactoring to ES6

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#21]
# Refactoring to ES6

We've talked a bit about ES6, "JavaScript NEXT", whatever you want to call it. Now it's time for us to start using it. I want you guys to take one of these previous assignments; Tic-Tac-Toe, Roshambo, TODOs, or Space Invaders, and convert it to use ES6.

If one of those assignments is outstanding for you, this is a good opportunity to complete it, because I'll accept this for both.

I'm not going to give specific instructions on how to setup or organize your ES6 transpiler, because that's part of this exercise. I think at this point, you should have the handle on your toolchain that you need to suss it out.  I'd suggest using [Babel](https://babeljs.io) and possibly `babel-gulp`.

**Comment by nickpizzo** [comment]
https://github.com/pizzounit/ES6Intro
