### ISSUE TITLE
Assignment 8-1 - List Maker (React)

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#28]
# List Maker (React)

Today in class we introduced React and built a trivial "List Maker".

Your task tonight is to take the class exercise and add the ability to remove an item from the list.
## Deliverables
- [ ] Deploy to GH Pages (`gulp deploy`).
## Explorer Mode
- [ ] Fork this repo to your own account.
- [ ] Add the ability to remove and item by clicking on it.

It's okay if there are multiple items with the same value to remove them all.

_**Hint**:_ `Array.prototype.filter`
## Adventure Mode

It's no longer okay to remove multiple items if you've only clicked on one.

_**Hint**:_ Maybe an additional `prop`?
## Epic Mode

Have your list items persist between reloads.

**Comment by nickpizzo** [comment]
http://pizzounit.github.io/ListMaker/
