### ISSUE TITLE
Assignment 1-2 - FizzBuzz

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#3]
## Week 1 - Assignment 2 - Fizz Buzz

The "Fizz-Buzz test" is an interview question designed to help filter out the 99.5% of programming job candidates who can't seem to program their way out of a wet paper bag. The text of the programming assignment is as follows:

> "Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”."
### Normal Mode

You'll need to use the `console.log()` function, as well as the remainder (modulo) operator: `%`. You'll also need to use a `for` loop and `if` conditionals.
- [x] Implement `FizzBuzz` as described above.
- [x] You should be able to successfully run your program and see the output, like: `node fizzbuzz.js`.
- [ ] You can turn in the assignment as a gist, just like day one's homework.
#### Additional Resources
- [Arithmetic Operators on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators), checkout the "Remainder" operator in particular. You'll need this one.
- A [Blog post](http://blog.codinghorror.com/why-cant-programmers-program/) from Jeff Atwood on why exercises like FizzBuzz are valuable, and why often given as technical interview questions.
### Adventure Mode
- [x] See if you can optimize the logic of your program to not include extra cases for printing "FizzBuzz" when the number is divisible by both 3 and 5. You should only have to check those once.
- [x] Turn in the homework as a full repository on Github. Put the git command line stuff we talked about in class today to work.

**Comment by nickpizzo** [comment]
https://github.com/pizzounit/day_two

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/z0w3I99Fk9icU/200w_d.gif)
