### ISSUE TITLE
Assignment 1-3 - Functions

### ISSUE THREAD

**Issue by ambethia** [nickpizzo/assignments#4]
### Objectives

After completing this assignment, you should be able to:
- Understand JS syntax
- Demonstrate understanding of types, functions, argument-handling, loops, and conditional statements
### Details

Instructions
- `cd` into your project folder
- `mkdir <projectName>`, e.g. 'day-3-functions'
- `git init`
- `curl -O https://gist.githubusercontent.com/ambethia/3d472a76f5da83fb5d71/raw/functions.js`
- `node functions.js`

Modify `functions.js` to make the tests/assertions pass.

**Note**: The first two problems are the last two we didn't finish in class.
### Normal Mode
- [x] All assertions in functions.js pass
- [x] Turn in the homework as a repository on Github. Link to it in a comment on this issue.
#### Additional Resources

You might need to reference these to find what kind of helpful functions might already be on `Array` and `String` in JavaScript.
- [String Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String).
- [Array Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).
### Adventure Mode
- [ ] If you used any methods like `Array`'s `.reverse()` in your solutions, implemet the functions again without them.
- [ ] If you didn't use many built-in functions, look through the MDN documentation linked above and see if you can make use of any to refactor your code.

**Comment by nickpizzo** [comment]
https://github.com/pizzounit/day_three

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/cNdY6ipQFeNuo/200w_d.gif)
